///////////////////////////////////////////////////////////
//  DateGoogleDataColumn.cs
//  Implementation of the Class DateGoogleDataColumn
//  Generated by Enterprise Architect
//  Created on:      12-Feb-2009 5:20:03 PM
//  Original author: Gary
// 
//  Copyright (c) 2009 Gary Bortosky. All rights reserved. 
// 
//  This library is free software; you can redistribute it and/or modify it
//  under the terms of the New BSD License, a copy of which should have
//  been delivered along with this distribution.
// 
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
//  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
//  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
//  PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
//  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
//  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
//  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
//  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
//  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
///////////////////////////////////////////////////////////



using System;
using System.Data;
using Bortosky.Google.Visualization.Columns;
namespace Bortosky.Google.Visualization.Columns {
	internal class DateGoogleDataColumn : GoogleDataColumn {

		/// 
		/// <param name="column"></param>
		internal DateGoogleDataColumn(DataColumn column): base(column){

		}

		/// 
		/// <param name="row"></param>
		protected internal override string SerializedValue(DataRow row){
            System.DateTime d = (System.DateTime)row[subjectColumn];
            return string.Format("new Date({0}, {1}, {2})", d.Year, d.Month - 1, d.Day);
        }

		protected internal override string GoogleDataType{
			get{
				return "date";
			}
		}

	}//end DateGoogleDataColumn

}//end namespace Columns